apiVersion: v1
kind: Service
metadata: 
  name: keycloak-svc
  namespace: keycloak
spec:
  selector:
    app: keycloak-dep
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: LoadBalancer
